defmodule NFTex.Chain do
  @moduledoc """
  High-level chain operations.

  Chains are containers for rules within a table. They can be either base chains
  (hooked directly into the kernel's netfilter framework) or regular chains
  (used for organizing rules and as jump targets).

  ## Chain Types

  ### Base Chains

  Base chains are directly hooked into netfilter and process packets at specific
  points in the network stack:

  - **INPUT** - Packets destined for local processes
  - **FORWARD** - Packets routed through the system
  - **OUTPUT** - Packets generated by local processes
  - **PREROUTING** - Packets as they arrive (before routing)
  - **POSTROUTING** - Packets as they leave (after routing)

  ### Regular Chains

  Regular chains are not hooked into netfilter. They organize rules and serve
  as jump targets from other rules.

  ## Hook Points and Chain Types

  Different hook points support different chain types:

  | Hook         | Filter | NAT | Route |
  |--------------|--------|-----|-------|
  | prerouting   | ✓      | ✓   | -     |
  | input        | ✓      | ✓   | -     |
  | forward      | ✓      | -   | -     |
  | output       | ✓      | ✓   | ✓     |
  | postrouting  | ✓      | ✓   | -     |

  ## Priority

  When multiple chains hook the same point, priority determines evaluation order.
  Lower numbers are evaluated first. Common priorities:

  - `-300` - Connection tracking
  - `-200` - Mangle (packet modification)
  - `-100` - DNAT
  - `0` - Filter (default)
  - `100` - Security
  - `200` - NAT
  - `300` - Mangle

  ## Quick Example

      {:ok, pid} = NFTex.start_link()

      # Create a base chain for filtering input packets
      :ok = NFTex.Chain.add(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept  # Default action if no rules match
      })

      # Create a regular chain for custom rules
      :ok = NFTex.Chain.add(pid, %{
        table: "filter",
        name: "my_custom_rules",
        family: :inet
      })

  ## Complete Firewall Setup

      # 1. Create table
      :ok = NFTex.Table.add(pid, %{name: "filter", family: :inet})

      # 2. Create INPUT chain
      :ok = NFTex.Chain.add(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # 3. Add rules
      :ok = NFTex.Rule.block_ip(pid, "filter", "INPUT", "192.168.1.100")

  ## Querying Chains

  To list existing chains, use `NFTex.Query.list_chains/2`:

      {:ok, chains} = NFTex.Query.list_chains(pid, family: :inet)

  ## Integration with nft Command

  Chains created with NFTex can be managed with the `nft` command:

      # Create with NFTex
      NFTex.Chain.add(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # View with nft
      $ nft list chain filter INPUT

      # Delete with nft
      $ nft delete chain filter INPUT

  ## See Also

  - `NFTex.Table` - Create tables to contain chains
  - `NFTex.Rule` - Add rules to chains
  - `NFTex.Query` - Query existing chains
  """

  alias NFTex.{Port, JSONBuilder}

  @type family :: :inet | :ip | :ip6 | :arp | :bridge | :netdev
  @type chain_type :: :filter | :nat | :route
  @type hook :: :prerouting | :input | :forward | :output | :postrouting | :ingress
  @type policy :: :accept | :drop
  @type base_chain_spec :: %{
          table: String.t(),
          name: String.t(),
          family: family(),
          type: chain_type(),
          hook: hook(),
          priority: integer(),
          policy: policy()
        }
  @type regular_chain_spec :: %{
          table: String.t(),
          name: String.t(),
          family: family()
        }
  @type chain_spec :: base_chain_spec() | regular_chain_spec()

  @doc """
  Add a chain.

  ## Base Chain Parameters

  - `table` - Table name (required)
  - `name` - Chain name (required)
  - `family` - Protocol family (required)
  - `type` - Chain type: `:filter`, `:nat`, or `:route` (required for base chains)
  - `hook` - Hook point (required for base chains)
  - `priority` - Chain priority (required for base chains)
  - `policy` - Default policy: `:accept` or `:drop` (required for base chains)

  ## Regular Chain Parameters

  - `table` - Table name (required)
  - `name` - Chain name (required)
  - `family` - Protocol family (required)

  ## Example

      # Base chain
      NFTex.Chain.add(pid, %{
        table: "filter",
        name: "input",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # Regular chain
      NFTex.Chain.add(pid, %{
        table: "filter",
        name: "my_rules",
        family: :inet
      })

  """
  @spec add(pid(), chain_spec()) :: :ok | {:error, term()}
  def add(pid, spec) do
    # Validate chain name
    cond do
      !Map.has_key?(spec, :name) ->
        {:error, :name_required}

      byte_size(spec.name) == 0 ->
        {:error, :empty_name}

      true ->
        create_chain(pid, spec)
    end
  end

  defp create_chain(pid, spec) do
    is_base_chain = Map.has_key?(spec, :hook)

    # Build chain options
    opts =
      if is_base_chain do
        [
          type: to_string(spec.type),
          hook: to_string(spec.hook),
          prio: spec.priority,
          policy: to_string(spec.policy)
        ]
      else
        []
      end

    # Build JSON command
    cmd = JSONBuilder.add_chain(spec.family, spec.table, spec.name, opts)
    json = Jason.encode!(cmd)

    # Send to port
    case Port.call(pid, json) do
      {:ok, ""} ->
        # Empty response means success
        :ok

      {:ok, response_json} ->
        # Parse response to check for errors
        case Jason.decode(response_json) do
          {:ok, %{"nftables" => _}} ->
            :ok

          {:ok, %{"error" => error}} ->
            {:error, error}

          {:error, reason} ->
            {:error, {:json_decode_failed, reason}}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Delete a chain.

  ## Example

      NFTex.Chain.delete(pid, "filter", "input", :inet)

  """
  @spec delete(pid(), String.t(), String.t(), family()) :: :ok | {:error, term()}
  def delete(pid, table, name, family) do
    # Build JSON command
    cmd = JSONBuilder.delete_chain(family, table, name)
    json = Jason.encode!(cmd)

    # Send to port
    case Port.call(pid, json) do
      {:ok, ""} ->
        # Empty response means success
        :ok

      {:ok, response_json} ->
        # Parse response to check for errors
        case Jason.decode(response_json) do
          {:ok, %{"nftables" => _}} ->
            :ok

          {:ok, %{"error" => error}} ->
            {:error, error}

          {:error, reason} ->
            {:error, {:json_decode_failed, reason}}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  List all chains for a given protocol family.

  This is a convenience function that calls `NFTex.Query.list_chains/2`.

  ## Parameters

  - `pid` - NFTex process pid
  - `opts` - Keyword list options:
    - `:family` - Protocol family (default: `:inet`)
    - `:parse` - Parse responses into structs (default: `true`)
    - `:timeout` - Operation timeout in ms (default: 5000)

  ## Examples

      {:ok, chains} = NFTex.Chain.list(pid)
      {:ok, chains} = NFTex.Chain.list(pid, family: :inet6)

      for c <- chains do
        IO.puts("Chain: \#{c.name} in table \#{c.table}")
      end

  """
  @spec list(pid(), keyword()) :: {:ok, [map()]} | {:error, term()}
  def list(pid, opts \\ []) do
    NFTex.Query.list_chains(pid, opts)
  end

  @doc """
  Check if a chain exists.

  ## Parameters

  - `pid` - NFTex process pid
  - `table` - Table name
  - `name` - Chain name
  - `family` - Protocol family (default: `:inet`)

  ## Examples

      if NFTex.Chain.exists?(pid, "filter", "INPUT", :inet) do
        IO.puts("Chain exists")
      end

  """
  @spec exists?(pid(), String.t(), String.t(), family()) :: boolean()
  def exists?(pid, table, name, family \\ :inet) do
    case NFTex.Query.list_chains(pid, family: family) do
      {:ok, chains} ->
        Enum.any?(chains, fn chain ->
          chain.name == name and chain.table == table
        end)

      {:error, _} ->
        false
    end
  end

  @doc """
  Set the default policy for a base chain.

  Note: This requires recreating the chain with the new policy.
  In nftables, policy is set at chain creation time.

  ## Parameters

  - `pid` - NFTex process pid
  - `table` - Table name
  - `name` - Chain name
  - `family` - Protocol family
  - `policy` - Policy (`:accept` or `:drop`)

  Note: Only base chains (chains with hooks) can have policies.

  ## Example

      :ok = NFTex.Chain.set_policy(pid, "filter", "INPUT", :inet, :drop)

  """
  @spec set_policy(pid(), String.t(), String.t(), family(), policy()) ::
          :ok | {:error, term()}
  def set_policy(_pid, _table, _name, _family, policy) when policy in [:accept, :drop] do
    # In the JSON API, policies are set at chain creation time
    # To change a policy, you need to delete and recreate the chain
    {:error, :policy_change_requires_recreation}
  end

  @doc """
  Build a JSON command to add a chain (without executing).

  Returns the JSON string that would be sent to add a chain.
  Useful for batching, remote execution, or inspection.

  ## Parameters

  - `spec` - Chain specification map (same as `add/2`)

  ## Returns

  JSON string containing the chain add command

  ## Examples

      # Build base chain command
      json = NFTex.Chain.build_add(%{
        table: "filter",
        name: "input",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })
      #=> "{\\\"nftables\\\":[{\\\"add\\\":{\\\"chain\\\":{...}}}]}"

      # Build regular chain command
      json = NFTex.Chain.build_add(%{
        table: "filter",
        name: "my_rules",
        family: :inet
      })

      # Use in batch
      batch =
        Batch.new()
        |> Batch.add(Chain.build_add(%{...}))
        |> Batch.add(Chain.build_add(%{...}))

      # Execute later
      NFTex.Executor.execute(json)
  """
  @spec build_add(chain_spec()) :: binary()
  def build_add(spec) do
    is_base_chain = Map.has_key?(spec, :hook)

    # Build chain options
    opts =
      if is_base_chain do
        [
          type: to_string(spec.type),
          hook: to_string(spec.hook),
          prio: spec.priority,
          policy: to_string(spec.policy)
        ]
      else
        []
      end

    # Build JSON command
    cmd = JSONBuilder.add_chain(spec.family, spec.table, spec.name, opts)
    Jason.encode!(cmd)
  end

  @doc """
  Build a JSON command to delete a chain (without executing).

  Returns the JSON string that would be sent to delete a chain.

  ## Parameters

  - `table` - Table name
  - `name` - Chain name
  - `family` - Protocol family

  ## Returns

  JSON string containing the chain delete command

  ## Examples

      json = NFTex.Chain.build_delete("filter", "input", :inet)
      NFTex.Executor.execute(json)
  """
  @spec build_delete(String.t(), String.t(), family()) :: binary()
  def build_delete(table, name, family) do
    cmd = JSONBuilder.delete_chain(family, table, name)
    Jason.encode!(cmd)
  end
end
