defmodule NFTex.Chain do
  @moduledoc """
  High-level chain operations with automatic resource management.

  Chains are containers for rules within a table. They can be either base chains
  (hooked directly into the kernel's netfilter framework) or regular chains
  (used for organizing rules and as jump targets).

  ## Chain Types

  ### Base Chains

  Base chains are directly hooked into netfilter and process packets at specific
  points in the network stack:

  - **INPUT** - Packets destined for local processes
  - **FORWARD** - Packets routed through the system
  - **OUTPUT** - Packets generated by local processes
  - **PREROUTING** - Packets as they arrive (before routing)
  - **POSTROUTING** - Packets as they leave (after routing)

  ### Regular Chains

  Regular chains are not hooked into netfilter. They organize rules and serve
  as jump targets from other rules.

  ## Hook Points and Chain Types

  Different hook points support different chain types:

  | Hook         | Filter | NAT | Route |
  |--------------|--------|-----|-------|
  | prerouting   | ✓      | ✓   | -     |
  | input        | ✓      | ✓   | -     |
  | forward      | ✓      | -   | -     |
  | output       | ✓      | ✓   | ✓     |
  | postrouting  | ✓      | ✓   | -     |

  ## Priority

  When multiple chains hook the same point, priority determines evaluation order.
  Lower numbers are evaluated first. Common priorities:

  - `-300` - Connection tracking
  - `-200` - Mangle (packet modification)
  - `-100` - DNAT
  - `0` - Filter (default)
  - `100` - Security
  - `200` - NAT
  - `300` - Mangle

  ## Quick Example

      {:ok, pid} = NFTex.start_link()

      # Create a base chain for filtering input packets
      :ok = NFTex.Chain.create(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept  # Default action if no rules match
      })

      # Create a regular chain for custom rules
      :ok = NFTex.Chain.create(pid, %{
        table: "filter",
        name: "my_custom_rules",
        family: :inet
      })

  ## Complete Firewall Setup

      # 1. Create table
      :ok = NFTex.Table.create(pid, %{name: "filter", family: :inet})

      # 2. Create INPUT chain
      :ok = NFTex.Chain.create(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # 3. Add rules
      :ok = NFTex.Rule.block_ip(pid, "filter", "INPUT", <<192, 168, 1, 100>>)

  ## Querying Chains

  To list existing chains, use `NFTex.Query.list_chains/2`:

      {:ok, chains} = NFTex.Query.list_chains(pid, family: :inet)

  ## Integration with nft Command

  Chains created with NFTex can be managed with the `nft` command:

      # Create with NFTex
      NFTex.Chain.create(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # View with nft
      $ nft list chain filter INPUT

      # Delete with nft
      $ nft delete chain filter INPUT

  ## See Also

  - `NFTex.Table` - Create tables to contain chains
  - `NFTex.Rule` - Add rules to chains
  - `NFTex.Query` - Query existing chains
  - `NFTex.Kernel.Chain` - Low-level chain operations
  """

  alias NFTex.Kernel

  @type family :: :inet | :ip | :ip6 | :arp | :bridge | :netdev
  @type chain_type :: :filter | :nat | :route
  @type hook :: :prerouting | :input | :forward | :output | :postrouting | :ingress
  @type policy :: :accept | :drop
  @type base_chain_spec :: %{
          table: String.t(),
          name: String.t(),
          family: family(),
          type: chain_type(),
          hook: hook(),
          priority: integer(),
          policy: policy()
        }
  @type regular_chain_spec :: %{
          table: String.t(),
          name: String.t(),
          family: family()
        }
  @type chain_spec :: base_chain_spec() | regular_chain_spec()

  @doc """
  Create a chain.

  ## Base Chain Parameters

  - `table` - Table name (required)
  - `name` - Chain name (required)
  - `family` - Protocol family (required)
  - `type` - Chain type: `:filter`, `:nat`, or `:route` (required for base chains)
  - `hook` - Hook point (required for base chains)
  - `priority` - Chain priority (required for base chains)
  - `policy` - Default policy: `:accept` or `:drop` (required for base chains)

  ## Regular Chain Parameters

  - `table` - Table name (required)
  - `name` - Chain name (required)
  - `family` - Protocol family (required)

  ## Example

      # Base chain
      NFTex.Chain.create(pid, %{
        table: "filter",
        name: "input",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # Regular chain
      NFTex.Chain.create(pid, %{
        table: "filter",
        name: "my_rules",
        family: :inet
      })

  """
  @spec create(pid(), chain_spec()) :: :ok | {:error, term()}
  def create(pid, spec) do
    # Validate chain name
    cond do
      !Map.has_key?(spec, :name) ->
        {:error, :name_required}

      byte_size(spec.name) == 0 ->
        {:error, :empty_name}

      true ->
        create_chain(pid, spec)
    end
  end

  defp create_chain(pid, spec) do
    is_base_chain = Map.has_key?(spec, :hook)

    # Allocate, configure, send to kernel, and cleanup
    with {:ok, chain_id} <- Kernel.Chain.alloc(pid),
         :ok <- Kernel.Chain.set_str(pid, chain_id, :table, spec.table),
         :ok <- Kernel.Chain.set_str(pid, chain_id, :name, spec.name),
         :ok <- Kernel.Chain.set_u32(pid, chain_id, :family, family_to_int(spec.family)),
         :ok <- maybe_set_base_chain_attrs(pid, chain_id, spec, is_base_chain),
         :ok <- Kernel.Chain.send_to_kernel(pid, chain_id, :add),
         :ok <- Kernel.Chain.free(pid, chain_id) do
      :ok
    else
      {:error, _reason} = error ->
        error
    end
  end

  @doc """
  Delete a chain.

  ## Example

      NFTex.Chain.delete(pid, "filter", "input", :inet)

  """
  @spec delete(pid(), String.t(), String.t(), family()) :: :ok | {:error, term()}
  def delete(pid, table, name, family) do
    # Allocate, configure, send delete to kernel, and cleanup
    with {:ok, chain_id} <- Kernel.Chain.alloc(pid),
         :ok <- Kernel.Chain.set_str(pid, chain_id, :table, table),
         :ok <- Kernel.Chain.set_str(pid, chain_id, :name, name),
         :ok <- Kernel.Chain.set_u32(pid, chain_id, :family, family_to_int(family)),
         :ok <- Kernel.Chain.send_to_kernel(pid, chain_id, :delete),
         :ok <- Kernel.Chain.free(pid, chain_id) do
      :ok
    else
      {:error, _reason} = error ->
        error
    end
  end

  # Private helpers

  defp family_to_int(:inet), do: 1
  defp family_to_int(:ip), do: 2
  defp family_to_int(:ip6), do: 10
  defp family_to_int(:arp), do: 3
  defp family_to_int(:bridge), do: 7
  defp family_to_int(:netdev), do: 5

  defp maybe_set_base_chain_attrs(pid, chain_id, spec, true) do
    with :ok <- Kernel.Chain.set_str(pid, chain_id, :type, to_string(spec.type)),
         :ok <- Kernel.Chain.set_u32(pid, chain_id, :hooknum, hook_to_int(spec.hook)),
         :ok <- Kernel.Chain.set_u32(pid, chain_id, :prio, encode_priority(spec.priority)),
         :ok <- Kernel.Chain.set_u32(pid, chain_id, :policy, policy_to_int(spec.policy)) do
      :ok
    end
  end

  defp maybe_set_base_chain_attrs(_pid, _chain_id, _spec, false) do
    # Regular chain, no additional attributes
    :ok
  end

  defp hook_to_int(:prerouting), do: 0
  defp hook_to_int(:input), do: 1
  defp hook_to_int(:forward), do: 2
  defp hook_to_int(:output), do: 3
  defp hook_to_int(:postrouting), do: 4
  defp hook_to_int(:ingress), do: 0

  defp policy_to_int(:drop), do: 0
  defp policy_to_int(:accept), do: 1

  # Priority is a signed 32-bit integer, but we use set_u32
  # For negative values, we need to convert to unsigned representation
  defp encode_priority(prio) when prio < 0 do
    # Convert negative to unsigned 32-bit representation
    0x100000000 + prio
  end

  defp encode_priority(prio) when prio >= 0, do: prio

  @doc """
  List all chains for a given protocol family.

  This is a convenience function that calls `NFTex.Query.list_chains/2`.

  ## Parameters

  - `pid` - NFTex process pid
  - `opts` - Keyword list options:
    - `:family` - Protocol family (default: `:inet`)
    - `:parse` - Parse responses into structs (default: `true`)
    - `:timeout` - Operation timeout in ms (default: 5000)

  ## Examples

      {:ok, chains} = NFTex.Chain.list(pid)
      {:ok, chains} = NFTex.Chain.list(pid, family: :inet6)

      for chain <- chains do
        IO.puts("Chain: \#{chain.name} in table \#{chain.table}")
      end

  """
  @spec list(pid(), keyword()) :: {:ok, [map()]} | {:error, term()}
  def list(pid, opts \\ []) do
    NFTex.Query.list_chains(pid, opts)
  end

  @doc """
  Check if a chain exists.

  ## Parameters

  - `pid` - NFTex process pid
  - `table` - Table name
  - `name` - Chain name
  - `family` - Protocol family (default: `:inet`)

  ## Examples

      if NFTex.Chain.exists?(pid, "filter", "INPUT", :inet) do
        IO.puts("Chain exists")
      end

  """
  @spec exists?(pid(), String.t(), String.t(), family()) :: boolean()
  def exists?(pid, table, name, family \\ :inet) do
    case NFTex.Query.list_chains(pid, family: family) do
      {:ok, chains} ->
        Enum.any?(chains, fn chain ->
          chain.name == name and chain.table == table
        end)

      {:error, _} ->
        false
    end
  end

  @doc """
  Set the default policy for a base chain.

  ## Parameters

  - `pid` - NFTex process pid
  - `table` - Table name
  - `name` - Chain name
  - `family` - Protocol family
  - `policy` - Policy (`:accept` or `:drop`)

  Note: Only base chains (chains with hooks) can have policies.
  Regular chains will return an error.

  ## Example

      :ok = NFTex.Chain.set_policy(pid, "filter", "INPUT", :inet, :drop)

  """
  @spec set_policy(pid(), String.t(), String.t(), family(), policy()) ::
          :ok | {:error, term()}
  def set_policy(pid, table, name, family, policy) when policy in [:accept, :drop] do
    policy_int = policy_to_int(policy)

    with {:ok, chain_id} <- Kernel.Chain.alloc(pid),
         :ok <- Kernel.Chain.set_str(pid, chain_id, :table, table),
         :ok <- Kernel.Chain.set_str(pid, chain_id, :name, name),
         :ok <- Kernel.Chain.set_u32(pid, chain_id, :family, family_to_int(family)),
         :ok <- Kernel.Chain.set_u32(pid, chain_id, :policy, policy_int),
         :ok <- Kernel.Chain.send_to_kernel(pid, chain_id, :add),
         :ok <- Kernel.Chain.free(pid, chain_id) do
      :ok
    else
      {:error, _reason} = error ->
        error
    end
  end
end
