defmodule NFTablesEx.Chain do
  @moduledoc """
  High-level chain operations.

  Chains are containers for rules within a table. They can be either base chains
  (hooked directly into the kernel's netfilter framework) or regular chains
  (used for organizing rules and as jump targets).

  ## Chain Types

  ### Base Chains

  Base chains are directly hooked into netfilter and process packets at specific
  points in the network stack:

  - **INPUT** - Packets destined for local processes
  - **FORWARD** - Packets routed through the system
  - **OUTPUT** - Packets generated by local processes
  - **PREROUTING** - Packets as they arrive (before routing)
  - **POSTROUTING** - Packets as they leave (after routing)

  ### Regular Chains

  Regular chains are not hooked into netfilter. They organize rules and serve
  as jump targets from other rules.

  ## Hook Points and Chain Types

  Different hook points support different chain types:

  | Hook         | Filter | NAT | Route |
  |--------------|--------|-----|-------|
  | prerouting   | ✓      | ✓   | -     |
  | input        | ✓      | ✓   | -     |
  | forward      | ✓      | -   | -     |
  | output       | ✓      | ✓   | ✓     |
  | postrouting  | ✓      | ✓   | -     |

  ## Priority

  When multiple chains hook the same point, priority determines evaluation order.
  Lower numbers are evaluated first. Common priorities:

  - `-300` - Connection tracking
  - `-200` - Mangle (packet modification)
  - `-100` - DNAT
  - `0` - Filter (default)
  - `100` - Security
  - `200` - NAT
  - `300` - Mangle

  ## Quick Example

      {:ok, pid} = NFTablesEx.start_link()

      # Create a base chain for filtering input packets
      :ok = NFTablesEx.Chain.add(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept  # Default action if no rules match
      })

      # Create a regular chain for custom rules
      :ok = NFTablesEx.Chain.add(pid, %{
        table: "filter",
        name: "my_custom_rules",
        family: :inet
      })

  ## Complete Firewall Setup

      # 1. Create table
      :ok = NFTablesEx.Table.add(pid, %{name: "filter", family: :inet})

      # 2. Create INPUT chain
      :ok = NFTablesEx.Chain.add(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # 3. Add rules
      :ok = NFTablesEx.Rule.block_ip(pid, "filter", "INPUT", "192.168.1.100")

  ## Querying Chains

  To list existing chains, use `NFTablesEx.Query.list_chains/2`:

      {:ok, chains} = NFTablesEx.Query.fetch_chains(pid, family: :inet)

  ## Integration with nft Command

  Chains created with NFTex can be managed with the `nft` command:

      # Create with NFTex
      NFTablesEx.Chain.add(pid, %{
        table: "filter",
        name: "INPUT",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # View with nft
      $ nft list chain filter INPUT

      # Delete with nft
      $ nft delete chain filter INPUT

  ## See Also

  - `NFTablesEx.Table` - Create tables to contain chains
  - `NFTablesEx.Rule` - Add rules to chains
  - `NFTablesEx.Query` - Query existing chains
  """

  @type family :: :inet | :ip | :ip6 | :arp | :bridge | :netdev
  @type chain_type :: :filter | :nat | :route
  @type hook :: :prerouting | :input | :forward | :output | :postrouting | :ingress
  @type policy :: :accept | :drop
  @type base_chain_spec :: %{
          table: String.t(),
          name: String.t(),
          family: family(),
          type: chain_type(),
          hook: hook(),
          priority: integer(),
          policy: policy()
        }
  @type regular_chain_spec :: %{
          table: String.t(),
          name: String.t(),
          family: family()
        }
  @type chain_spec :: base_chain_spec() | regular_chain_spec()

  @doc """
  Add a chain.

  ## Base Chain Parameters

  - `table` - Table name (required)
  - `name` - Chain name (required)
  - `family` - Protocol family (required)
  - `type` - Chain type: `:filter`, `:nat`, or `:route` (required for base chains)
  - `hook` - Hook point (required for base chains)
  - `priority` - Chain priority (required for base chains)
  - `policy` - Default policy: `:accept` or `:drop` (required for base chains)

  ## Regular Chain Parameters

  - `table` - Table name (required)
  - `name` - Chain name (required)
  - `family` - Protocol family (required)

  ## Example

      # Base chain
      NFTablesEx.Chain.add(pid, %{
        table: "filter",
        name: "input",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })

      # Regular chain
      NFTablesEx.Chain.add(pid, %{
        table: "filter",
        name: "my_rules",
        family: :inet
      })

  """
  @spec add(pid(), chain_spec()) :: :ok | {:error, term()}
  def add(pid, spec) do
    # Validate chain name
    cond do
      !Map.has_key?(spec, :name) ->
        {:error, :name_required}

      byte_size(spec.name) == 0 ->
        {:error, :empty_name}

      true ->
        build_add(spec)
        |> NFTablesEx.Executor.execute(pid: pid)
        |> NFTablesEx.Decoder.decode()
    end
  end

  @doc """
  Delete a chain.

  ## Parameters

  - `pid` - NFTex process pid
  - `table` - Table name (string)
  - `name` - Chain name (string)
  - `family` - Protocol family (default: `:inet`)

  ## Example

      :ok = NFTablesEx.Chain.delete(pid, "filter", "input", :inet)

  """
  @spec delete(pid(), String.t(), String.t(), family()) :: :ok | {:error, term()}
  def delete(pid, table, name, family \\ :inet) do
    build_delete(table, name, family)
    |> NFTablesEx.Executor.execute(pid: pid)
    |> NFTablesEx.Decoder.decode()
  end

  @doc """
  Set the default policy for a base chain.

  Note: This requires recreating the chain with the new policy.
  In nftables, policy is set at chain creation time.

  ## Parameters

  - `pid` - NFTex process pid
  - `table` - Table name
  - `name` - Chain name
  - `family` - Protocol family
  - `policy` - Policy (`:accept` or `:drop`)

  Note: Only base chains (chains with hooks) can have policies.

  ## Example

      :ok = NFTablesEx.Chain.set_policy(pid, "filter", "INPUT", :inet, :drop)

  """
  @spec set_policy(pid(), String.t(), String.t(), family(), policy()) ::
          :ok | {:error, term()}
  def set_policy(_pid, _table, _name, _family, policy) when policy in [:accept, :drop] do
    # In the JSON API, policies are set at chain creation time
    # To change a policy, you need to delete and recreate the chain
    {:error, :policy_change_requires_recreation}
  end

  @doc """
  Build a command map to add a chain (without executing).

  Returns a map that would be sent to add a chain.
  Useful for batching, remote execution, or inspection.

  ## Parameters

  - `spec` - Chain specification map (same as `add/2`)

  ## Returns

  Map containing the chain add command

  ## Examples

      # Build base chain command
      cmd = NFTablesEx.Chain.build_add(%{
        table: "filter",
        name: "input",
        family: :inet,
        type: :filter,
        hook: :input,
        priority: 0,
        policy: :accept
      })
      #=> %{"nftables" => [%{"add" => %{"chain" => ...}}]}

      # Build regular chain command
      cmd = NFTablesEx.Chain.build_add(%{
        table: "filter",
        name: "my_rules",
        family: :inet
      })

      # Use in batch
      batch =
        Batch.new()
        |> Batch.add(Chain.build_add(%{...}))
        |> Batch.add(Chain.build_add(%{...}))

      # Execute later
      NFTablesEx.Executor.execute(cmd)
  """
  @spec build_add(chain_spec()) :: map()
  def build_add(spec) do
    is_base_chain = Map.has_key?(spec, :hook)

    # Build chain spec
    chain_spec =
      if is_base_chain do
        %{
          "family" => spec.family,
          "table" => spec.table,
          "name" => spec.name,
          "type" => spec.type,
          "hook" => spec.hook,
          "prio" => spec.priority,
          "policy" => spec.policy
        }
      else
        %{
          "family" => spec.family,
          "table" => spec.table,
          "name" => spec.name
        }
      end

    # Build command map
    %{
      "nftables" => [
        %{
          "add" => %{
            "chain" => chain_spec
          }
        }
      ]
    }
  end

  @doc """
  Build a command map to delete a chain (without executing).

  Returns a map that would be sent to delete a chain.

  ## Parameters

  - `table` - Table name
  - `name` - Chain name
  - `family` - Protocol family

  ## Returns

  Map containing the chain delete command

  ## Examples

      cmd = NFTablesEx.Chain.build_delete("filter", "input", :inet)
      NFTablesEx.Executor.execute(cmd)
  """
  @spec build_delete(String.t(), String.t(), family()) :: map()
  def build_delete(table, name, family) do
    %{
      "nftables" => [
        %{
          "delete" => %{
            "chain" => %{
              "family" => family,
              "table" => table,
              "name" => name
            }
          }
        }
      ]
    }
  end
end
